POST http://localhost:3001/auth/register
content-type: application/json

{
    "name": "Carlos",
    "email": "carlos4@carlos.com.br",
    "password": "super secure password"
}

###

POST http://localhost:3001/auth/login
content-type: application/json

{
    "email": "carlos4@carlos.com.br",
    "password": "super secure password"
}

###

GET http://localhost:3001/user/598f2de2-e7e3-48b2-a857-f606157ffe41
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhcmxvczRAY2FybG9zLmNvbS5iciIsInN1YiI6eyJuYW1lIjoiQ2FybG9zIn0sImlhdCI6MTcyMDQ3NDMwNiwiZXhwIjoxNzIwNDc3OTA2fQ.puaDL8w__dpmiSeF1EQThatbbzHZtT280pVF3c8wwk8